services:
  - type: web
    name: ecom-launchpad-backend
    env: docker # Tell Render to use our Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATAIMPULSE_USER
        sync: false
      - key: DATAIMPULSE_PASS
        sync: false